version: "3"

networks:
  grafana:

volumes:
  app_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:2.4.2
    restart: unless-stopped
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.0.0
    restart: unless-stopped
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  grafana:
    build: ./grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - "GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt" # adjust to match your domain name
      - "GF_SERVER_CERT_KEY=/etc/grafana/grafana.key" # adjust to match your domain name
      - "GF_SERVER_PROTOCOL=https"

  app:
    build: ./app
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    restart: unless-stopped
    ports:
      - 8082:80
    networks:
      - grafana
