networks:
  grafana:

volumes:
  app_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v3.4.1
    restart: unless-stopped
    command:
      - "--storage.tsdb.retention.time=1d"
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - grafana

  loki:
    image: grafana/loki:3.4.4
    restart: unless-stopped
    networks:
      - grafana

  grafana:
    build: ./grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - "GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt" # adjust to match your domain name
      - "GF_SERVER_CERT_KEY=/etc/grafana/grafana.key" # adjust to match your domain name
      - "GF_SERVER_PROTOCOL=https"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=cloud2025"

  app:
    build: ./app
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    restart: unless-stopped
    networks:
      - grafana

  alloy:
    image: grafana/alloy:v1.9.1
    restart: unless-stopped
    cap_add:
      - SYS_TIME
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      # Logs
      - app_data:/app/logs
      # Config
      - ./alloy:/etc/alloy
    networks:
      - grafana