version: "3"

networks:
  grafana:

volumes:
  app_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.45.6
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - grafana

  loki:
    image: grafana/loki:2.9.9
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.9.9
    restart: unless-stopped
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  grafana:
    build: ./grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - "GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt" # adjust to match your domain name
      - "GF_SERVER_CERT_KEY=/etc/grafana/grafana.key" # adjust to match your domain name
      - "GF_SERVER_PROTOCOL=https"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=cloud2023"

  app:
    build: ./app
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana

  db:
    image: grafana/tns-db:latest
    restart: unless-stopped
    networks:
      - grafana

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - grafana
