global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "node"

    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "tns_app"

    # Override global settings
    scrape_interval: 5s

    static_configs:
      - targets: ["app:80"]
